# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3c985fd1b5ccf53ad8dd4af8e9f1628fa7151ad170593cbe59a83f69f35c27696f63948259bea07ce399e1c4015c26a72cb13c96b056856dab0156ea8da897a

test:
  secret_key_base: 1533aa9293f6a3e69db26fe948208f2232c79d62b20e766b391eb10c9745c545ab9fef537ac80d1e08cd3d6df0e378aaf02b1f739661b886160f08093f6ecb23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
